shop/urls.py
from django.conf.urls.defaults import patterns, include, url

urlpatterns = patterns('snapshop.shop.views',
    url(r'^$', 'search', name="search"),
    url(r'^results/$', 'results', name="results"),
    url(r'^sign-up/$', 'sign_up', name="sign_up"),
    url(r'^thanks/$', 'thanks', name="thanks"),
    url(r'^save_cart/$', 'save_cart', name="save_cart"),
    url(r'^view-item/(?P<item_id>.*)/$', 'view_item', name="view_item"),
    url(r'^account/$', 'account', name="account"),
    url(r'^browse/$', 'category_view', name="category_view"),
)

urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth import login

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'', include('snapshop.shop.urls')),
    url(r'^home/', 'snapshop.views.home', name='home'),

    #url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', name='logout'),
    # temporary logout fix: Otherwise directs to Django admin logout instead of
    # auth.views.logout (that would use registration/logged_out.html template)
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout_then_login', name='logout'),

    url(r'^accounts/', include('django.contrib.auth.urls')),
    # Django auth URLs must be after logout, otherwise wil override to admin logout

    # Examples:
    # url(r'^$', 'snapshop.views.home', name='home'),
    # url(r'^snapshop/', include('snapshop.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += staticfiles_urlpatterns()

shop/models.py
from django.db import models
from django.core.cache import cache
from django.contrib.auth.models import User
from django.core import serializers
from django.conf import settings
import requests
import json
from django import forms
from django.contrib.auth.forms import UserCreationForm

class ShopItem(models.Model):
    item_category = models.ForeignKey('Categories')
    item_name = models.CharField(max_length = 200)
    item_price = models.IntegerField(default = 99999)
    item_size = models.CharField(max_length=50)
    item_unit_price = models.CharField(max_length=50)
    item_thumb_small = models.CharField(max_length=200)
    item_thumb_medium = models.CharField(max_length=200)
    item_thumb_large = models.CharField(max_length=200)
    item_peapod_productid = models.CharField(max_length=50)
    item_peapod_cnid = models.CharField(max_length=20)
    item_nutrition_html = models.TextField()
    item_description_html = models.TextField()
    item_ingredients_html = models.TextField()
    item_details_html = models.TextField()

    @classmethod
    def _redis_key(cls,query):
        return "ShopItem:::%s" % query

    @classmethod
    def search(cls,query=""):
        results = []
        redis_key = cls._redis_key(query)

        if not cache.has_key(redis_key):
            res = requests.get("%s/search/%s/" % (settings.SCRAPER_ENDPOINT,query))
            if res.status_code == 200:
                result_names = res.json()['results']
                results = sorted(cls.objects.filter(item_name__in=result_names),
                                 key=lambda x: result_names.index(x.item_name))

            #go back to primitive search
            if not results:
                results = ShopItem.objects.filter(item_name__icontains=query)

            #save IDs of shop items in cache
            cache.set(redis_key,serializers.serialize("json",results),timeout=3600)

        else:
            results = [s.object for s in serializers.deserialize("json",cache.get(redis_key))]

        return results

class ShippingLabel(models.Model):
    address_first_line = models.CharField(max_length=50)
    address_second_line = models.CharField(max_length=50)
    address_zip_code = models.IntegerField()
    address_city = models.CharField(max_length=50)
    address_state = models.CharField(max_length=2)
    address_owner = models.ForeignKey('Customer')

class CreditCard(models.Model):
    cc_stub = models.CharField(max_length=4, default="****")
    cc_type = models.IntegerField(default=0)
    cc_owner = models.ForeignKey('Customer')

class Categories(models.Model):
    category_thumb = models.CharField(max_length=200)
    category_name = models.CharField(max_length=50)
    category_cnid = models.CharField(max_length=50)
    category_parent = models.ForeignKey('Categories', default=None, null=True)

class CartItem(models.Model):
    shop_item_ref = models.ForeignKey(ShopItem)
    cart = models.ForeignKey('ShoppingCart')
    cart_item_qty = models.IntegerField(default=0)

class ShoppingCart(models.Model):
    cart_owner = models.OneToOneField('Customer')

# Should create upon registration, along with shipping ShippingLabel
class Customer(models.Model):
    stripe_token = models.CharField(max_length=20)
    phone_number = models.CharField(max_length=20)
    delivery_time = models.DateTimeField()
    user = models.OneToOneField(User)

class PurchaseForm(forms.Form):
    PAYMENT_CHOICES = (
        ('save_new', 'Please remember my card for future orders'),
        ('no_save', "Don't remember my card for future orders"),
        ('use_old', 'Use my saved card'),
    )

    DORM_CHOICES = (
        #('362 Memorial Drive', 'Baker House'),
        #('450 Memorial Drive', 'MacGregor House'),
        #('3 Ames Street', 'East Campus'),
        ('460 Beacon Street', 'Nu Delta'),
        ('450 Beacon Street', 'Pi Lambda Phi'),
    )

    EXPIRATION_MONTH_CHOICES = (
        ('1', '01 - January'),
        ('2', '02 - February'),
        ('3', '03 - March'),
        ('4', '04 - April'),
        ('5', '05 - May'),
        ('6', '06 - June'),
        ('7', '07 - July'),
        ('8', '08 - August'),
        ('9', '09 - September'),
        ('10', '10 - October'),
        ('11', '11 - November'),
        ('12', '12 - December'),
    )

    EXPIRATION_YEAR_CHOICES = (
        ('2013', '2013'),
        ('2014', '2014'),
        ('2015', '2015'),
        ('2016', '2016'),
        ('2017', '2017'),
        ('2018', '2018'),
        ('2019', '2019'),
        ('2020', '2020'),
    )

    name = forms.CharField(max_length=50, widget=forms.TextInput({'placeholder':'Alyssa P. Hacker'}))
    living_group = forms.ChoiceField(DORM_CHOICES)
    room_number = forms.CharField(required=False, max_length=10, widget=forms.TextInput({'placeholder':'818'}))
    phone_number = forms.CharField(required=False, max_length=20, widget=forms.TextInput({'placeholder':'617 555 5555'}))
    #email = forms.CharField(max_length=32, widget=forms.TextInput({'placeholder':'any@mit.edu address'}))
    #address_2 = models.CharField(max_length=50)
    #city = models.CharField(max_length=50)
    #state = models.CharField(max_length=50)
    #zip_code = models.CharField(max_length=50)
    payment_choices = forms.ChoiceField(choices=PAYMENT_CHOICES) # overriden in views if logged in
    card_number = forms.CharField(required=False, max_length=20, widget=forms.TextInput({'placeholder':'4012888888881881'}))
    card_cvc = forms.CharField(required=False, max_length=4, widget=forms.TextInput({'placeholder':'626'}))
    card_zip = forms.CharField(required=False, max_length=5, widget=forms.TextInput({'placeholder':'02139'}))
    card_expiration_month = forms.ChoiceField(EXPIRATION_MONTH_CHOICES)
    card_expiration_year = forms.ChoiceField(EXPIRATION_YEAR_CHOICES)
    # promo_code = forms.CharField(required=False, max_length=10) # optional field
    items_list = forms.CharField(widget=forms.HiddenInput())    # JSON object with {'item_id': 'qty'}

class RegisterForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget = forms.TextInput({'placeholder':'MIT Email', 'class': 'large-input'})
        self.fields['password1'].widget = forms.PasswordInput({'placeholder':'Password', 'class': 'large-input'})
        self.fields['password2'].widget = forms.PasswordInput({'placeholder':'Confirm password', 'class': 'large-input'})

    def is_valid(self, *args, **kwargs):
        return super(RegisterForm, self).is_valid(*args, **kwargs)

    def save(self):
        user = super(RegisterForm, self).save(commit=True)
        user.is_active = True
        user.save()

shop/templates/account.html
{% extends "basepage.html" %}

{% block content %}
<div class="container page">
  <div class="page-header">
    <h2 class="lightweight"><img src="{{STATIC_URL}}img/user.png" /> My Account</h2>
  </div>
  <div class="page-body">
    <div class="tabbable tabs-left">
      <ul class="nav nav-tabs">
	<li class="active">
	  <a href="#basic-information" data-toggle="tab">Basic Information</a>
	</li>
	<li>
	  <a href="#payments" data-toggle="tab">Payments</a>
	</li>
      </ul>
      <div class="tab-content">
	<div class="tab-pane active" id="basic-information">
	  <h3 class="lightweight">Basic Information</h3>
	  <hr />
	  <div class="row-fluid">
	    <div class="span6">
	      <h4>Recent Orders</h4>
	      <table class="table table-striped">
		<thead>
		  <th>Order Name</th>
		  <th>ETA</th>
		  <th>Location</th>
		</thead>
		<tbody>
		  <tr>
		    <td>My Order #1 <a href="#"><i class="icon-search"></i></td>
		    <td>March 27th, 8 p.m.</td>
		    <td>Burton Conner</td>
		  </tr>
		  <tr>
		    <td>My Order #2 <a href="#"><i class="icon-search"></i></td>
		    <td>April 1st, 8 p.m.</td>
		    <td>Burton Conner</td>
		  </tr>
		  <tr>
		    <td>My Order #3 <a href="#"><i class="icon-search"></i></td>
		    <td>April 4th, 8 p.m.</td>
		    <td>Burton Conner</td>
		  </tr>
		</tbody>		    
	      </table>
	    </div>
	    <div class="span5">
	      <div class="well well-small">
		<h4>User Information <small><a href="#">(edit)</a></small></h4>
		<table class="table">
		  <tr>
		    <td><b>Name: </b></td>
		    <td>{{user.username}}</td>
		  </tr>
		  <tr>
		    <td><b>Dorm: </b></td>
		    <td>Burton Conner</td>
		  </tr>
		  <tr>
		    <td><b>Email Address: </b></td>
		    <td>rob@mopub.com</td>
		  </tr>
		  <tr>
		    <td><b>Phone Number: </b></td>
		    <td>999-999-9999</td>
		  </tr>
		</table>
	      </div>
	    </div>
	  </div>
	</div>
	<div class="tab-pane" id="payments">
	  <h3 class="lightweight">Payments</h3>
	  <hr />
	  <div class="row-fluid">
	    <div class="span5">
	      <h4>Current Payment Method <small><a href="#">(update)</a></small></h4>
	      <table class="table table-striped">
		<tr>
		  <td>Card Type</td>
		  <td>Visa</td>
		</tr>
		<tr>
		  <td>Card #</td>
		  <td>*********2234</td>
		</tr>
		<tr>
		  <td>Card Expiry</td>
		  <td>10/14</td>
		</tr>
		<tr>
		  <td>Billing Address</td>
		  <td>
		    <address>
		      <strong>Twitter, Inc.</strong><br>
		      795 Folsom Ave, Suite 600<br>
		      San Francisco, CA 94107<br>
		      <abbr title="Phone">P:</abbr> (123) 456-7890
		    </address>
		  </td>
		</tr>
	      </table>
	    </div>
	    <div class="span6">
	      <h4>Order History</h4>
	      <table class="table">
		<thead>
		  <th>Date</th>
		  <th>Name</th>
		  <th>Amount</th>
		</thead>
		<tbody>
		  <tr>
		    <td>12/13/12</td>
		    <td>Carrots and Onions</td>
		    <td>$13</td>
		  </tr>
		  <tr>
		    <td>12/17/12</td>
		    <td>Carrots and Onions</td>
		    <td>$13</td>
		  </tr>
		  <tr>
		    <td>12/21/12</td>
		    <td>Carrots and Onions</td>
		    <td>$13</td>
		  </tr>
		</tbody>
	      </table>
	    </div>
	  </div>	      
	</div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

shop/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <link rel="shortcut icon" href="{{STATIC_URL}}img/logo_light_blue.ico" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{{STATIC_URL}}css/bootstrap.min.css" rel="stylesheet" />
    <link href="{{STATIC_URL}}css/bootstrap-responsive.min.css" rel="stylesheet" />
    <link href="{{STATIC_URL}}css/bootstrapSwitch.css" rel="stylesheet" />
    <link href="{{STATIC_URL}}css/chosen.css" rel="stylesheet" />
    <link href="{{STATIC_URL}}css/snapshot.css" rel="stylesheet" />
    <script src="{{STATIC_URL}}js/jquery-1.9.1.min.js"></script>
    <script src="{{STATIC_URL}}js/bootstrapSwitch.js"></script>
    <script src="{{STATIC_URL}}js/bootstrap.min.js"></script>
    <script src="{{STATIC_URL}}js/chosen.jquery.min.js"></script>
    <script src="{{STATIC_URL}}js/snapshop.js"></script>

    <title>SnapShop</title>
  </head>

  <body>
    {% block body %}
    {% endblock %}
    <div id="preview-modal-container"></div>
  </body>
</html>

shop/templates/basepage.html
{% extends  "base.html" %}

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-39854714-1', 'snapshopmit.com');
  ga('send', 'pageview');

</script>

{% block body %}
<div class="splash">
  <div class="navbar navbar-fixed-top navbar-inverse">
    <div class="navbar-inner">
      <div class="container">
	<form id="navbar-form">
	  <ul class="nav">
	    <li><a href="{% url 'search' %}"><img src="{{STATIC_URL}}img/logo-thumb.png" /></a></li>
	    <li><a href="#">
		<select name="q" class="chzn-select" style="width:600px" data-placeholder="Search..." multiple>
		{% for keyword,shop_items in keyword_item_map.items %}
		<option selected value="{{keyword}}">{{keyword}}</option>
		{% endfor %}
	      </select>
	      </a>
	    </li>
	    <li>
	      <a id="submit-navbar-form" href="#"><button class="submit btn btn-primary btn-small"><i class="icon-shopping-cart icon-white"></i>Find your groceries</button></a>
	    </li>
	  </ul>
	  <ul class="nav pull-right">
	    <li><a href="{% url 'account' %}"><i class="icon-user icon-white"></i> {{user.username}}</a></li>
	  </ul>
	</form>
      </div>
    </div>
  </div>
  {% block content %}
  {% endblock %}
</div>
{% endblock %}

shop/templates/category.html
{% extends "base.html" %}

{% block body %}
<div class="splash">
  <div class="container-fluid full-height">
    <div class="row-fluid full-height">
      <div class="span3">
      </div>
      <div class="span6 full-height">
    <div class="well half-height rob-box">
      <div class="rob-header">
      </div>
      <div class="rob-body">

        <!-- left column, for all categories -->
        <table>

        {% for category in categories_top %}
          <tr> <td id="{{ category.category_cnid }}">
            <!-- category.image TODO need to find/scrape -->
            {{ category.category_name }}
          </td></tr>
        {% endfor %}

        </table>


      </div>
    </div>
      </div>
      <div class="span3">
      </div>
    </div>
  </div>
</div>
{% endblock %}

shop/templates/index.html
{% extends "base.html" %}

{% block body %}
<div class="splash">
  <div class="container-fluid">
    <div class="row-fluid">
      <div class="span4">
      </div>
      <div class="span4">
  <div class="half-height">
    <form action="{% url 'sign_up' %}" method="POST">
      <div class="rob-box well">
        <div class="rob-header">
        </div>
        <div class="rob-body">
          {{ form.non_field_errors }}
          {% csrf_token %}
          <center>
            <p class="muted">Already have an account? <a href="{% url 'login' %}">Login here</a></p>
          <fieldset>
            {% for field in form %}
            <div class="control-group">
              {{ field.errors }}
              {{ field }}
            </div>
            {% endfor %}
          </fieldset>
          </center>
    <div class="row-fluid" id="tos-section">
      <div class="offset1 span6">
        <i class="muted lightweight">
          Would you love to receive product updates and announcements from the snapshop team?
        </i>
      </div>
      <div class="offset1 span3">
        <div id="tos-switch" class="switch switch-large" data-on-label="LOVE" data-off-label="sad :(">
          <input checked type="checkbox">
        </div>
      </div>
    </div>
    <hr />
    <button class="btn btn-large btn-block btn-primary" type="submit">Sign up now!</button>
        </div>
    </form>
    </div>
      </div>
      <div class="span4">
      </div>
    </div>
  </div>
</div>
{% endblock %}

shop/templates/item_modal.html
<div class="modal hide fade">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3>{{item.item_name}}</h3>
  </div>
  <div class="modal-body">
    <table class="table">
      <tr>
	<td><b>Name</b></td>
	<td>{{item.item_name}}</td>
      </tr>
      <tr>
	<td><b>Price</b></td>
	<td>{{item.item_price}}</td>
      </tr>
      <tr>
	<td><b>Size</b></td>
	<td>{{item.item_size}}</td>
      </tr>
      <tr>
	<td colspan="2">
	  <img src="{{item.item_thumb_large}}" />
	</td>
      </tr>
    </table>
  </div>
  <div class="modal-footer">
    <a href="#" data-dismiss="modal" class="btn">Close</a>
  </div>
</div>

shop/templates/main.html
{% extends "basepage.html" %}
{% load snapshop_tags %}
{% load shop_extras %}

{% block content %}
<div class="container page">
  <div class="page-header">
    <h2 class="lightweight"><img src="{{STATIC_URL}}img/search.png" /> Here's what we've found for you...</h2>
  </div>
  <div class="page-body">
    <div class="ingredient-box" >
      {% if keyword_item_map.keys %}
      {% for keyword,shop_items in keyword_item_map.items %}
      <div id="{{keyword|idify}}-container" class="ingredient-list-container">
	<div class="navbar">
	  <div class="navbar-inner">
	    <a class="brand" href="#"><i class="icon-tags"></i> {{keyword}}</a>
	    <ul class="nav pull-right">
	      <li><a href="#"><i data-containerid="{{keyword|idify}}-container" class="icon-chevron-left index-back" data-target="ingredient-list-{{keyword|idify}}"></i></a></li>
	      <li><a href="#" id="{{keyword|idify}}-index">1</a></li>
	      <li><a href="#"><i data-containerid="{{keyword|idify}}-container" class="icon-chevron-right index-forward" data-target="ingredient-list-{{keyword|idify}}"></i></a></li>
	      <li class="divider"></li>
	      <li><a><i data-containerid="{{keyword|idify}}-container" class="icon-remove remove-ingredient-list"></i></a></li>
	    </ul>
	  </div>
	</div>
	<div id="ingredient-list-{{keyword|idify}}" class="ingredient-list" data-page="0" data-keyword="{{keyword|idify}}">
	  <div class="row-fluid">
	    {% for item in shop_items %}
	    {% if forloop.first %}
	    <div id="row-{{keyword|idify}}-{{forloop.counter0}}" class="row-{{keyword|idify}} ingredient-row">
	      {% else %}
	      {% if forloop.counter0|divisibleby:10 %}
	    </div>
	    <div id="row-{{keyword|idify}}-{{forloop.counter0|divide:10}}" class="hide row-{{keyword|idify}} ingredient-row">
	      {% endif %}
	      {% endif %}
	      <div class="span1 ingredient-item" data-item-name="{{item.item_name}}" data-item-price="{{item.item_price}}" data-item-id="{{item.pk}}" data-item-size="{{item.item_size}}">
		<span class="ingredient-badge badge badge-success">{{item.item_price|pretty_price}}</span>
		<img class="ingredient-thumbnail tooltipped" data-title="{{item.item_name}} ({{item.item_size}}) - {{item.item_price|pretty_price}}" src="{{item.item_thumb_medium}}" />
	      </div>
	      {% if forloop.last %}
	    </div>
	    {% endif %}
	    {% endfor %}
	  </div>
	</div>
      </div>
      {% endfor %}
      {% else %}
      <p class="muted">No matching keywords for query {{query}}</p>
      {% endif %}
    </div>
    <hr class="thick"/>
    <div class="cart-box">
      <div class="subpage-header">
	<h2><img src="{{STATIC_URL}}img/cart.png" /> Ingredients Cart</h2>
      </div>
      <table id="cart-table" class="table">
	<thead>
	  <th class="cart-name">Name</th>
	  <th class="cart-quantity">Quantity</th>
	  <th class="cart-amount">Amount</th>
	  <th class="cart-actions">Actions</th>
	</thead>

	<tbody>
          {% for row in cart %}
          <tr data-item-price="{{row.1.item_price}}" data-item-id="{{row.1.pk}}">
            <td><img src="{{row.1.item_thumb_medium}}" width="24" height="24"/> {{row.1.item_name}} ({{row.1.item_size}}) <i class="icon-search view-item-icon"></i></td>
            <td class="quantity">{{row.0}}</td>
            <td class="price">{{row.1.item_price | pretty_price}}</td>
            <td>
              <i class="icon-chevron-down decrease-quantity-icon"></i> <i class="icon-chevron-up increase-quantity-icon"></i><i class="icon-remove remove-item-icon"></i>
            </td>
          </tr>
          {% endfor %}

	  <tr class="summary-row">
	    <td><b>Total: </b></td>
	    <td></td>
	    <td><b>{{cart_total | pretty_price}}</b></td>
	    <td></td>
	  </tr>
	</tbody>

      </table>
    </div>
  </div>
  <hr class="thick"/>


  <div class="purchase-form-box">
    <div class="subpage-header">
      <h2><img src="{{STATIC_URL}}img/purchase.png" /> Purchase Form</h2>
    </div>
    <p>Order by 5PM Friday, April 5 for delivery on Saturday, April 6. We currently ship to the following MIT living groups: Pi Lambda Phi, Nu Delta. Our next shipment date will be Saturday, April 27 with more locations.</p>
    {% if user.is_authenticated %}
    <p>Your credit card will not be charged until your groceries ship. If you have placed an order with us before, simply select your card below.</p>
    <p><br /></p>
    <form id="purchase-form" class="form-horizontal" action="{% url 'results' %}" method="post">
      {% csrf_token %}
      {{ form.non_field_errors }}
      {% for field in form.visible_fields %}
      <div class="control-group">
        {{ field.errors }}
        <label class="control-label" for="{{ field.html_name }}">
          {{ field.label }} {% if field.field.required %}*{% endif %}</label>
        <div class="controls">
          {{ field }}
        </div>
      </div>
      {% endfor %}
      <p>* fields are required</p>
      <!--{{ form.items_list }}-->
      <input type="hidden" id="id_items_list" name='items_list' value='{{cart_json}}'></input><!-- Required for saving cart -->
      <div class="form-actions">
        <button type="submit" class="btn btn-primary"><i class="icon-white icon-home"></i> Order my Groceries</button>
      </div>

      {% else %}
      <p>Please <a href="{% url 'login' %}?next={{request.path}}">log in</a> or <a href="{% url 'sign_up' %}?next={{request.path}}">sign up</a> before making a purchase</p>
      <input type="hidden" id="id_items_list" name='item_list' value='{{cart_json}}'></input><!-- Required for saving cart -->
      {% endif %}


    </form>

  </div>
</div>
{% endblock %}

shop/templates/search.html
{% extends "base.html" %}

{% block body %}
<div class="splash">
  <div class="container-fluid full-height">
    <div class="row-fluid full-height">
      <div class="span3">
      </div>
      <div class="span6 full-height">
	<div class="well half-height rob-box">
	  <div class="rob-header">
	  </div>
	  <div class="rob-body">
	    <form action="{% url 'results' %}" method="GET">
	      <center>
		<p class="muted">
		  {% if user.is_authenticated %}
		  Welcome {{user.username}}! How is your day? <a href="{% url 'logout' %}">Logout</a>
		  {% else %}
		  Not logged in? <a href="{% url 'login' %}">Login here</a>.  or no account? <a href="{% url 'sign_up' %}">Sign up</a>
		  {% endif %}
		</p>
		<p class="muted">Order by 5PM Friday, April 5 for delivery on April 6 to: Nu Delta, Pi Lambda Phi. Our next shipment date will be Saturday, April 27 with more locations.</p>
		<select name="q" data-placeholder="Enter a list e.g.: apple, granola bar, whole milk" multiple class="chzn-select full-width">
		</select>
		<button class="submit btn btn-primary"><i class="icon-shopping-cart icon-white"></i>Find your groceries</button>

	    </center>
	    </form>
	  </div>
	</div>
      </div>
      <div class="span3">
      </div>
    </div>
  </div>
</div>
{% endblock %}

shop/templates/thanks.html
{% extends "base.html" %}

{% block body %}

<div class="splash">
  <div class="container page">
    <div class="page-header">
      <h1>Thank you for your order!</h1>
    </div>
    <div class="page-body">
    </div>
  </div>
</div>

{% endblock %}